### ISSUE TITLE
[DISCUSSION] using h2 or sqlite ? 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/Snipper#1]
Since we are saving stuff locally, keeping a mongodb server running is cumbersome (and might have issues on different operating systems).
How about using a file-based db like h2db or sqlite ? 

@piyush0 thoughts ?

**Comment by piyush0** [comment]
https://github.com/louischatriot/nedb

How about this? This will solve the purpose of not creating a server and is a subset of Mongo's API.
