### ISSUE TITLE
new feature : seperate hotkeys for seperate snips

### ISSUE THREAD

**Issue by akansh97531** [coding-blocks/Snipper#11]
Users can register their own key combinations to copy particular snip to clipboard without going to GUI
@piyush0

**Comment by akansh97531** [comment]
@championswimmer please add bounty

**Comment by piyush0** [comment]
Which snip will be copied on key combination ?

**Comment by akansh97531** [comment]
user can specify key combination for any snip they want

**Comment by piyush0** [comment]
Okay, you can start working on this

**Comment by akansh97531** [comment]
#13  done

**Comment by piyush0** [comment]
Solved by @akansh97531 in #13

**Comment by akansh97531** [comment]
@championswimmer please add bounty

**Comment by akansh97531** [comment]
@championswimmer please add bounty

**Comment by akansh97531** [comment]
@championswimmer 
please add bounty
