### ISSUE TITLE
add github gist support

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/Snipper#17]
- [ ] login with github
- [ ] add a snip to github as a gist (use a `snipper-filename-date.extension convension`)
- [ ] sync existing gists into snipper (those that start with `snipper-`)

**Comment by prateekiiest** [comment]
@championswimmer , could you pls explain a little bit about what needs to be done exactly?

**Comment by abhishek97** [comment]
@championswimmer pls review https://github.com/coding-blocks/Snipper/pull/21
