### ISSUE TITLE
let's use Bootstrap 4

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/Snipper#18]
looks slicker and more modern than bootstrap 3, and is pretty stable now. we can migrate

**Comment by prateekiiest** [comment]
So this includes all the files under bootstrap to be converted to version 4 , right?

**Comment by asutosh97** [comment]
@championswimmer  I have created a [PR](https://github.com/coding-blocks/Snipper/compare/master...asutosh97:bootstrap4?expand=1) for this issue. Please review it.

**Comment by himanshuc3** [comment]
Is this still open? Assign me this if it is available to work upon.

**Comment by championswimmer** [comment]
Yes it is open to work upon.

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by vinayd1** [comment]
Can I work on this issue if no one is working on it?

**Comment by championswimmer** [comment]
Sure go ahead
