### ISSUE TITLE
create an icon for this app

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/Snipper#19]
objects that can inspire the logo - 
 - snip = scissor maybe? 
 - code/programming (that's what the snippets are about)
 - list (because we see the snips in a list).

**Comment by HarshKhatore** [comment]
@championswimmer Could you share the details?

**Comment by prateekiiest** [comment]
@championswimmer 

- [scissor] 

- [code ] 

- [list] 

All three satisfied

Pls have a look at this logo.

![snipperlogo](https://user-images.githubusercontent.com/16035442/28754059-9d028490-755b-11e7-9f5a-5875604748b0.png)

**Comment by HarshKhatore** [comment]
@prateekiiest This looks good.
Can you tell me the tools used to create such logo images?

**Comment by 0xnmn** [comment]
@championswimmer @omerjerk how is this one ? I have created a svg too. This one is png. 

![image](https://user-images.githubusercontent.com/22571395/28755693-08c7d488-757e-11e7-8461-4cb5d8972590.png)

**Comment by prateekiiest** [comment]
@HarshKhatore 
you can find many online editing tools for this.
Mine is available in both png and svg format.

**Comment by championswimmer** [comment]
@hereisnaman 
your one looks good. make a PR with both png and SVG

**Comment by ArushiSinghal** [comment]
@championswimmer 
a)
![imageedit_5_8002960085](https://user-images.githubusercontent.com/20858804/28934662-62505a6a-789f-11e7-8d3f-a5f99ba96359.jpg)
b)
![imageedit_1_8756345849](https://user-images.githubusercontent.com/20858804/28934673-6a367bec-789f-11e7-889d-1a52b9e7ffac.png)

**Comment by 0xnmn** [comment]
@championswimmer I just need to add the icons of all three types png, ico and icns (mac) and of all the resolutions in the assets right ?
