### ISSUE TITLE
create packaging/installation setup for Windows

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/Snipper#2]

**Comment by championswimmer** [comment]
use electron-builder and electron-packager

**Comment by adarsh1021** [comment]
![snipper large file](https://cloud.githubusercontent.com/assets/22254286/26753572/c6fa220a-4886-11e7-8764-27a9b6d8956a.png)

Hello ! I am getting this error while pushing. It says large file size.
I created the build using electron-packager 
Kindly look into this and let me know if there is something I am doing wrong.

**Comment by piyush0** [comment]
Check if the build file can be compressed further. Otherwise, host the file somewhere else and put the link here.

**Comment by adarsh1021** [comment]
I converted the build file to installer. Still git is not letting me push. Same error.
I have uploaded the installer file here : 
https://drive.google.com/open?id=0ByRx7tG5q3dfSHZMX3VTWm02bnM

**Comment by akansh97531** [comment]
#16 @championswimmer
