### ISSUE TITLE
Issue: Supports Only javaScript

### ISSUE THREAD

**Issue by vinayd1** [coding-blocks/Snipper#24]
While adding a new Snip It gives an error for code written in languages other than JavaScript
![code](https://user-images.githubusercontent.com/30961698/41157305-f8d17b4a-6b42-11e8-9dcc-645f8691ee97.png)
![error](https://user-images.githubusercontent.com/30961698/41157307-f8ff68e8-6b42-11e8-97c9-c2e58037e3a0.png)
![js](https://user-images.githubusercontent.com/30961698/41157309-f92e9aa0-6b42-11e8-9309-86b910b65293.png)

**Comment by architkshk** [comment]
@championswimmer Done!! #26
